import React, { useState, useRef, useEffect } from 'react';
import { ThreeDotsIcon } from './icons';

const InfoMenu: React.FC = () => {
    const [isOpen, setIsOpen] = useState(false);
    const menuRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
                setIsOpen(false);
            }
        };

        document.addEventListener('mousedown', handleClickOutside);
        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, []);

    const menuItems = [
        {
            title: 'About Flagship Chart',
            content: (
                <>
                    <p className="mb-2">Flagship Chart, part of the Flagship 2.0 project, is an experimental tool by FlyBoat Creative.</p>
                    <p><strong>How It Works:</strong></p>
                    <ol className="list-decimal list-inside text-sm space-y-1">
                        <li>You provide details about your professional experience, education, skills, and interests.</li>
                        <li>Our AI analyses your unique profile to identify your core strengths and transferable skills.</li>
                        <li>We generate a personalised "career chart" showing potential career paths that align with your profile, allowing you to explore new possibilities.</li>
                    </ol>
                    <p className="mt-3 text-xs text-slate-500">FlyBoat Creative</p>
                </>
            ),
        },
        {
            title: 'Your Data & Privacy',
            content: (
                <>
                    <p className="mb-2">We are committed to protecting your privacy. The information you enter is used solely to generate your career profile and is not stored or saved by this application.</p>
                    <p className="mb-2">Your data is sent to the Google Gemini API for processing. Google may use this data as described in their <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-sky-400 underline">Privacy Policy</a> and <a href="https://ai.google/gemini-api/docs/data-governance" target="_blank" rel="noopener noreferrer" className="text-sky-400 underline">API Data Governance</a> terms.</p>
                    <p>By using this tool, you acknowledge and agree to these terms.</p>
                </>
            ),
        },
        {
            title: 'Terms & Disclaimers',
            content: (
                <>
                    <p className="mb-2">Flagship Chart is an experimental tool provided for information purposes only. The content generated by the AI—including career paths, salary data, and skill requirements—should be considered a starting point for your own research and not as definitive professional career advice.</p>
                    <p className="mb-2">We make no guarantees regarding the accuracy, completeness, or suitability of the information provided. Flagship Chart does not guarantee employment, salary levels, or career success.</p>
                     <p>Your use of this service is at your own risk. We are not liable for any decisions made based on the information provided by this tool.</p>
                </>
            ),
        },
        {
            title: 'Help & Feedback',
            content: (
                <>
                    <p>Have questions, ideas, or feedback? We'd love to hear from you!</p>
                    <p className="mt-2">Please reach out to us at: <a href="mailto:hello@flyboat.online" className="text-sky-400 underline">hello@flyboat.online</a></p>
                </>
            ),
        },
    ];

    return (
        <div className="relative" ref={menuRef}>
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="p-2 rounded-full text-slate-400 hover:bg-slate-700 hover:text-slate-100 transition-colors duration-200 ease-in-out"
                aria-label="Information Menu"
            >
                <ThreeDotsIcon className="w-6 h-6" />
            </button>

            {isOpen && (
                <div className="absolute top-full right-0 mt-2 w-80 bg-slate-800 rounded-lg shadow-xl border border-slate-700 z-50 animate-in fade-in zoom-in-95">
                    <div className="p-2">
                        {menuItems.map((item, index) => (
                            <details key={index} className="group rounded-lg hover:bg-slate-700/50 transition-colors duration-200 ease-in-out">
                                <summary className="p-3 font-semibold text-slate-200 cursor-pointer list-none flex justify-between items-center">
                                    {item.title}
                                    <svg className="w-4 h-4 text-slate-400 group-open:rotate-180 transition-transform duration-300 ease-in-out" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path></svg>
                                </summary>
                                <div className="px-3 pb-3 text-slate-400 text-sm">
                                    {item.content}
                                </div>
                            </details>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
};

export default InfoMenu;
